config/routes.rb
Rails.application.routes.draw do
  resources :wrthmas
  root "wrthmas#index"
  end # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/wrthma.rb
class Wrthma < ApplicationRecord
  has_one_attached :picture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/wrthmas_controller.rb
class WrthmasController < ApplicationController
  before_action :set_wrthma, only: [:show, :edit, :update, :destroy]

  # GET /wrthmas
  # GET /wrthmas.json
  def index
    @wrthmas = Wrthma.all
  end

  # GET /wrthmas/1
  # GET /wrthmas/1.json
  def show
  end

  # GET /wrthmas/new
  def new
    @wrthma = Wrthma.new
  end

  # GET /wrthmas/1/edit
  def edit
  end

  # POST /wrthmas
  # POST /wrthmas.json
  def create
    @wrthma = Wrthma.new(wrthma_params)

    respond_to do |format|
      if @wrthma.save
        format.html { redirect_to @wrthma, notice: 'Wrthma was successfully created.' }
        format.json { render :show, status: :created, location: @wrthma }
      else
        format.html { render :new }
        format.json { render json: @wrthma.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wrthmas/1
  # PATCH/PUT /wrthmas/1.json
  def update
    respond_to do |format|
      if @wrthma.update(wrthma_params)
        format.html { redirect_to @wrthma, notice: 'Wrthma was successfully updated.' }
        format.json { render :show, status: :ok, location: @wrthma }
      else
        format.html { render :edit }
        format.json { render json: @wrthma.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wrthmas/1
  # DELETE /wrthmas/1.json
  def destroy
    @wrthma.destroy
    respond_to do |format|
      format.html { redirect_to wrthmas_url, notice: 'Wrthma was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wrthma
      @wrthma = Wrthma.find(params[:id])

    end

    # Only allow a list of trusted parameters through.
    def wrthma_params
      params.require(:wrthma).permit(:name, :title, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wrthmas_helper.rb
module WrthmasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>writing.through.material</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<div class="wtm">
<div class="writing">
  <%= link_to 'http://meetingwords.com/Yvbpl4FuSU'  do %>
      <i class="fa fa-pencil" style="font-size: 2em; color: black;"></i>
  <% end %>
</div>

   <div class="a">a<br></div>

   <div class="aa">a<br></div>

   <div class="e">e<br></div>

   <div class="g">g<br></div>

   <div class="gg">g<br></div>

   <div class="h">h<br></div>

   <div class="hh">h<br></div>

   <div class="i">i<br></div>

   <div class="ii">i<br></div>

   <div class="iii">i<br></div>

   <div class="l">l<br></div>

   <div class="m">m<br></div>

   <div class="n">n<br></div>

   <div class="o">o<br></div>

   <div class="r">r<br></div>

   <div class="rr">r<br></div>

   <div class="rrr">r<br></div>

   <div class="t">t<br></div>

   <div class="tt">t<br></div>

   <div class="ttt">t<br></div>

   <div class="u">u<br></div>

   <div class="w">w<br></div>

   <div class="dot">.<br></div>

   <div class="dotdot">.<br></div>
</div>
   <%= yield %>

  </body>
</html>

app/views/wrthmas/_form.html.erb
<%= form_with(model: wrthma, local: true) do |form| %>
  <% if wrthma.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wrthma.errors.count, "error") %> prohibited this wrthma from being saved:</h2>

      <ul>
        <% wrthma.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wrthmas/edit.html.erb
<h1>Editing Wrthma</h1>

<%= render 'form', wrthma: @wrthma %>

<%= link_to 'Show', @wrthma %> |
<%= link_to 'Back', wrthmas_path %>
<%= image_tag @wrthma.picture %>
s

app/views/wrthmas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wrthmas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wrthmas.each do |wrthma| %>
      <tr>
        <td><%= wrthma.name %></td>
        <td><%= wrthma.title %></td>
        <td><%= link_to 'Show', wrthma %></td>
        <td><%= link_to 'Edit', edit_wrthma_path(wrthma) %></td>
        <td><%= link_to 'Destroy', wrthma, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wrthma', new_wrthma_path %>

app/views/wrthmas/new.html.erb
<h1>New Wrthma</h1>

<%= render 'form', wrthma: @wrthma %>

<%= link_to 'Back', wrthmas_path %>

app/views/wrthmas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wrthma.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @wrthma.title %>
</p>


<iframe src=<%= url_for(@wrthma.picture) %> width="700" height="780" style="border: none;"></iframe>

<%= link_to 'Edit', edit_wrthma_path(@wrthma) %> |
<%= link_to 'Back', wrthmas_path %>